# Generated by Django 2.2.13 on 2020-06-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
