# Generated by Django 2.2.13 on 2020-07-15 02:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Consulta')),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fecha consulta',
                'verbose_name_plural': 'fechas consultas',
            },
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.CreateModel(
            name='HoraConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora de Consulta')),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('fecha_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.FechaConsulta', verbose_name='Fecha de Consulta')),
            ],
            options={
                'verbose_name': 'hora consulta',
            },
        ),
    ]
