# Generated by Django 2.2.13 on 2020-07-16 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20200714_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaconsulta',
            name='fecha_consulta',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_consulta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Consulta'),
        ),
        migrations.DeleteModel(
            name='FechaConsulta',
        ),
        migrations.DeleteModel(
            name='HoraConsulta',
        ),
    ]
