# Generated by Django 2.2.13 on 2020-06-30 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_especialidades_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='fecha_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialidades',
            name='fecha_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualizacion'),
            preserve_default=False,
        ),
    ]
