# Generated by Django 2.2.13 on 2020-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20200630_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='fecha_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
